export ns=default
alias k='kubectl -n $ns'
alias kdo='k --dry-run=client -o yaml'
alias kdor='kdo --restart=Never'
alias kaf='kubectl apply -f'
alias kdf='kubectl delete -f'

source <(kubectl completion bash)
complete -F __start_kubectl k
complete -F __start_kubectl kdo
complete -F __start_kubectl kdor

alias kt='k run --rm -it busybox --image=busybox --restart=Never'
alias ktw='kt -- wget -O- --timeout 2'
